theme: jekyll-theme-cayman
project:
    name: Apollon77 GitHub Home
    tagline: GitHub Home for all Apollon77 projects
site:
    title: Apollon77 GitHub Home
    description: GitHub Home for all Apollon77 projects
